In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

torch.__version__

c:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\tqdm\auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


'1.12.1+cpu'

In [2]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim

0

In [4]:
scalar.item()

7

In [5]:
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [6]:
vector.ndim

1

In [7]:
MATRIX = torch.tensor([[7, 7,], [7, 7]])
MATRIX

tensor([[7, 7],
        [7, 7]])

In [8]:
MATRIX.ndim

2

In [9]:
MATRIX.shape

torch.Size([2, 2])

In [10]:
TENSOR = torch.tensor([[[1, 2, 3], [3, 4, 5], [5, 6, 7]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 4, 5],
         [5, 6, 7]]])

In [11]:
TENSOR.shape

torch.Size([1, 3, 3])

RANDOM TENSORS

In [12]:
random_tensor = torch.rand(3, 4, 3)
random_tensor

tensor([[[0.6375, 0.2753, 0.0185],
         [0.9301, 0.6328, 0.7020],
         [0.9340, 0.6789, 0.7525],
         [0.0935, 0.0373, 0.7502]],

        [[0.9804, 0.5460, 0.3233],
         [0.8593, 0.0725, 0.1644],
         [0.0786, 0.2892, 0.7570],
         [0.7986, 0.0126, 0.8318]],

        [[0.7556, 0.7506, 0.5709],
         [0.4492, 0.5301, 0.6038],
         [0.2527, 0.6174, 0.8198],
         [0.0051, 0.0168, 0.4836]]])

In [13]:
random_image_size_tensor = torch.rand(244, 244, 3)
random_image_size_tensor

tensor([[[0.7720, 0.5138, 0.2065],
         [0.7254, 0.1603, 0.4588],
         [0.3922, 0.5280, 0.8069],
         ...,
         [0.6932, 0.6798, 0.4625],
         [0.0270, 0.2573, 0.0467],
         [0.3335, 0.8371, 0.3565]],

        [[0.2572, 0.5340, 0.6976],
         [0.9727, 0.1126, 0.4165],
         [0.5162, 0.8248, 0.2854],
         ...,
         [0.2056, 0.4015, 0.4938],
         [0.9949, 0.0424, 0.5881],
         [0.8432, 0.5000, 0.9690]],

        [[0.8144, 0.1323, 0.8243],
         [0.9010, 0.9279, 0.2136],
         [0.9797, 0.9093, 0.0763],
         ...,
         [0.2767, 0.0846, 0.2906],
         [0.0783, 0.6050, 0.3589],
         [0.7452, 0.7894, 0.7264]],

        ...,

        [[0.3956, 0.4159, 0.2659],
         [0.9826, 0.8458, 0.5996],
         [0.8367, 0.7635, 0.6593],
         ...,
         [0.4183, 0.8571, 0.3360],
         [0.9926, 0.2345, 0.9456],
         [0.3228, 0.7929, 0.2609]],

        [[0.8395, 0.9184, 0.7669],
         [0.5081, 0.3240, 0.1263],
         [0.

In [14]:
zeros = torch.zeros(3, 4, 3)
ones = torch.ones(3, 4, 3)

In [15]:
zeros, ones

(tensor([[[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],
 
         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],
 
         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]]]),
 tensor([[[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]],
 
         [[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]],
 
         [[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]]]))

In [16]:
random_tensor * zeros

tensor([[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]])

RANGE OF TENSORS

In [17]:
some_range = torch.arange(0, 11, 2)
some_range

tensor([ 0,  2,  4,  6,  8, 10])

In [18]:
five_zeroes = torch.zeros_like(some_range)
five_zeroes

tensor([0, 0, 0, 0, 0, 0])

TENSOR DATATYPES

In [19]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0], dtype=None,
                                                device=None,
                                                requires_grad=False 
                                                )
float_32_tensor

tensor([3., 6., 9.])

In [20]:
float_16_tensor = torch.tensor([3, 6, 9], dtype=torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [21]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

INFORMATIONS ABOUT TENSOR

In [22]:
some_tensor = torch.rand(3, 4)

In [23]:
some_tensor.dtype, some_tensor.shape, some_tensor.size(), some_tensor.device

(torch.float32, torch.Size([3, 4]), torch.Size([3, 4]), device(type='cpu'))

TENSOR OPERATIONS

In [24]:
tensor = torch.tensor([1, 2, 3])
tensor + 100

tensor([101, 102, 103])

In [25]:
tensor * 10

tensor([10, 20, 30])

In [26]:
tensor - 10

tensor([-9, -8, -7])

In [27]:
tensor * tensor

tensor([1, 4, 9])

In [28]:
torch.mul(tensor, 10), torch.add(tensor, 10)

(tensor([10, 20, 30]), tensor([11, 12, 13]))

In [29]:
torch.matmul(tensor, tensor)

tensor(14)

In [30]:
tensor @ tensor

tensor(14)

SHAPE ERRORS

In [31]:
tensor_1 = torch.tensor([[1, 2], [3, 4], [5, 6]])
tensor_2 = tensor_1

# torch.mm(tensor_1, tensor_2) ERROR 3x2, 3x2

In [32]:
tensor_2.T, tensor_2

(tensor([[1, 3, 5],
         [2, 4, 6]]),
 tensor([[1, 2],
         [3, 4],
         [5, 6]]))

In [33]:
torch.mm(tensor_1, tensor_2.T)

tensor([[ 5, 11, 17],
        [11, 25, 39],
        [17, 39, 61]])

TENSOR AGREGATION

In [34]:
tensor = torch.arange(0, 100, 10)

In [35]:
torch.min(tensor), tensor.min()

(tensor(0), tensor(0))

In [36]:
torch.max(tensor), tensor.max()

(tensor(90), tensor(90))

In [37]:
# torch.mean(tensor) ERROR dtype
torch.mean(tensor.type(torch.float32)), tensor.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [38]:
torch.sum(tensor), tensor.sum()

(tensor(450), tensor(450))

In [39]:
tensor.argmin(), tensor.argmax()

(tensor(0), tensor(9))

RESHAPING

In [40]:
tensor = torch.arange(1, 10)
tensor, tensor.shape

(tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]), torch.Size([9]))

In [41]:
tensor_reshaped = tensor.reshape(1, 3, 3)
tensor_reshaped, tensor_reshaped.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [42]:
tensor_view = tensor.view(3, 3)
tensor_view, tensor

(tensor([[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]),
 tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]))

In [43]:
tensor_view[:, 0] = 5
tensor_view, tensor

(tensor([[5, 2, 3],
         [5, 5, 6],
         [5, 8, 9]]),
 tensor([5, 2, 3, 5, 5, 6, 5, 8, 9]))

In [44]:
tensors_stacked = torch.stack([tensor, tensor, tensor, tensor], dim=0)
tensors_stacked

tensor([[5, 2, 3, 5, 5, 6, 5, 8, 9],
        [5, 2, 3, 5, 5, 6, 5, 8, 9],
        [5, 2, 3, 5, 5, 6, 5, 8, 9],
        [5, 2, 3, 5, 5, 6, 5, 8, 9]])

In [45]:
unsqueezed = torch.unsqueeze(tensors_stacked, -1)
unsqueezed.size(), tensors_stacked.size()

(torch.Size([4, 9, 1]), torch.Size([4, 9]))

In [46]:
unsqueezed, tensors_stacked

(tensor([[[5],
          [2],
          [3],
          [5],
          [5],
          [6],
          [5],
          [8],
          [9]],
 
         [[5],
          [2],
          [3],
          [5],
          [5],
          [6],
          [5],
          [8],
          [9]],
 
         [[5],
          [2],
          [3],
          [5],
          [5],
          [6],
          [5],
          [8],
          [9]],
 
         [[5],
          [2],
          [3],
          [5],
          [5],
          [6],
          [5],
          [8],
          [9]]]),
 tensor([[5, 2, 3, 5, 5, 6, 5, 8, 9],
         [5, 2, 3, 5, 5, 6, 5, 8, 9],
         [5, 2, 3, 5, 5, 6, 5, 8, 9],
         [5, 2, 3, 5, 5, 6, 5, 8, 9]]))

In [47]:
torch.squeeze(unsqueezed).size(), unsqueezed.size()

(torch.Size([4, 9]), torch.Size([4, 9, 1]))

In [48]:
permuted = torch.permute(unsqueezed, [0, 2, 1])
permuted.size(), unsqueezed.size()

(torch.Size([4, 1, 9]), torch.Size([4, 9, 1]))

In [49]:
permuted, unsqueezed

(tensor([[[5, 2, 3, 5, 5, 6, 5, 8, 9]],
 
         [[5, 2, 3, 5, 5, 6, 5, 8, 9]],
 
         [[5, 2, 3, 5, 5, 6, 5, 8, 9]],
 
         [[5, 2, 3, 5, 5, 6, 5, 8, 9]]]),
 tensor([[[5],
          [2],
          [3],
          [5],
          [5],
          [6],
          [5],
          [8],
          [9]],
 
         [[5],
          [2],
          [3],
          [5],
          [5],
          [6],
          [5],
          [8],
          [9]],
 
         [[5],
          [2],
          [3],
          [5],
          [5],
          [6],
          [5],
          [8],
          [9]],
 
         [[5],
          [2],
          [3],
          [5],
          [5],
          [6],
          [5],
          [8],
          [9]]]))

In [50]:
unsqueezed[0, 0, 0] = 10 # PERMUTED WILL ALSO CHANGE

In [51]:
permuted[0, 0, 0], unsqueezed[0, 0, 0]

(tensor(10), tensor(10))

INDEXING


In [52]:
tensor = torch.arange(1, 10).reshape(1, 3, 3)
tensor

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [53]:
tensor[0], tensor[0][0], tensor[0][0][0]

(tensor([[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]),
 tensor([1, 2, 3]),
 tensor(1))

In [54]:
tensor[:, 2]

tensor([[7, 8, 9]])

PYTORCH & NUMPY

In [55]:
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)

array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [56]:
array.dtype, torch.arange(1.0, 2.0).dtype

(dtype('float64'), torch.float32)

In [57]:
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [58]:
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [59]:
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

REPRODUCIBILITY

In [63]:
tensor_a = torch.rand(3, 4)
tensor_b = torch.rand(3, 4)

tensor_a == tensor_b

tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In [65]:
RANDOM_SEED = 42

torch.manual_seed(RANDOM_SEED)
tensor_c = torch.rand(3, 4)
torch.manual_seed(RANDOM_SEED)
tensor_d = torch.rand(3, 4)

tensor_c == tensor_d

tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

GPU

In [67]:
torch.cuda.is_available()

False

In [68]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'
device

'cpu'

In [69]:
torch.cuda.device_count()

0

In [72]:
tensor = torch.tensor([1, 2, 3], device='cpu')
tensor, tensor.device

(tensor([1, 2, 3]), device(type='cpu'))

In [74]:
tensor_device = tensor.to(device)
tensor_device.device

device(type='cpu')

In [ ]:
# NUMPY DOESN'T WORK WITH GPU, FIRST MOVE IT TO CPU