In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

torch.__version__

c:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\tqdm\auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


'1.12.1+cpu'

In [3]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [5]:
scalar.item()

7

In [6]:
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [7]:
vector.ndim

1

In [8]:
MATRIX = torch.tensor([[7, 7,], [7, 7]])
MATRIX

tensor([[7, 7],
        [7, 7]])

In [9]:
MATRIX.ndim

2

In [10]:
MATRIX.shape

torch.Size([2, 2])

In [11]:
TENSOR = torch.tensor([[[1, 2, 3], [3, 4, 5], [5, 6, 7]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 4, 5],
         [5, 6, 7]]])

In [12]:
TENSOR.shape

torch.Size([1, 3, 3])

RANDOM TENSORS

In [13]:
random_tensor = torch.rand(3, 4, 3)
random_tensor

tensor([[[0.6863, 0.2574, 0.0941],
         [0.3261, 0.9337, 0.4303],
         [0.3563, 0.9464, 0.6370],
         [0.9872, 0.2328, 0.1547]],

        [[0.7450, 0.4775, 0.4182],
         [0.4810, 0.5823, 0.3848],
         [0.4096, 0.4440, 0.4708],
         [0.1572, 0.1749, 0.5100]],

        [[0.6788, 0.4384, 0.5604],
         [0.0721, 0.5788, 0.8924],
         [0.7919, 0.2667, 0.2648],
         [0.7307, 0.3845, 0.4416]]])

In [14]:
random_image_size_tensor = torch.rand(244, 244, 3)
random_image_size_tensor

tensor([[[0.7723, 0.4378, 0.2772],
         [0.9873, 0.9410, 0.4468],
         [0.4910, 0.5911, 0.7031],
         ...,
         [0.5557, 0.7790, 0.5334],
         [0.2782, 0.0659, 0.1380],
         [0.2382, 0.6974, 0.4673]],

        [[0.6279, 0.3160, 0.8127],
         [0.9948, 0.1713, 0.2929],
         [0.8251, 0.2164, 0.3896],
         ...,
         [0.1072, 0.5988, 0.4068],
         [0.8936, 0.3805, 0.4491],
         [0.2633, 0.1362, 0.2669]],

        [[0.0656, 0.5949, 0.1531],
         [0.1730, 0.7422, 0.8131],
         [0.8835, 0.8483, 0.5205],
         ...,
         [0.4355, 0.1200, 0.0920],
         [0.9464, 0.9557, 0.0706],
         [0.8215, 0.8696, 0.5490]],

        ...,

        [[0.5942, 0.1863, 0.4101],
         [0.5886, 0.4213, 0.9413],
         [0.4973, 0.9125, 0.0898],
         ...,
         [0.5776, 0.3586, 0.9554],
         [0.4080, 0.6291, 0.4433],
         [0.4521, 0.8435, 0.9310]],

        [[0.7780, 0.5280, 0.8395],
         [0.7233, 0.9375, 0.6858],
         [0.

In [15]:
zeros = torch.zeros(3, 4, 3)
ones = torch.ones(3, 4, 3)

In [16]:
zeros, ones

(tensor([[[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],
 
         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],
 
         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]]]),
 tensor([[[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]],
 
         [[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]],
 
         [[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]]]))

In [17]:
random_tensor * zeros

tensor([[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]])

RANGE OF TENSORS

In [32]:
some_range = torch.arange(0, 11, 2)
some_range

tensor([ 0,  2,  4,  6,  8, 10])

In [33]:
five_zeroes = torch.zeros_like(some_range)
five_zeroes

tensor([0, 0, 0, 0, 0, 0])

TENSOR DATATYPES

In [42]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0], dtype=None,
                                                device=None,
                                                requires_grad=False 
                                                )
float_32_tensor

tensor([3., 6., 9.])

In [43]:
float_16_tensor = torch.tensor([3, 6, 9], dtype=torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [45]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

INFORMATIONS ABOUT TENSOR

In [46]:
some_tensor = torch.rand(3, 4)

In [49]:
some_tensor.dtype, some_tensor.shape, some_tensor.size(), some_tensor.device

(torch.float32, torch.Size([3, 4]), torch.Size([3, 4]), device(type='cpu'))

TENSOR OPERATIONS

In [58]:
tensor = torch.tensor([1, 2, 3])
tensor + 100

tensor([101, 102, 103])

In [59]:
tensor * 10

tensor([10, 20, 30])

In [60]:
tensor - 10

tensor([-9, -8, -7])

In [61]:
tensor * tensor

tensor([1, 4, 9])

In [63]:
torch.mul(tensor, 10), torch.add(tensor, 10)

(tensor([10, 20, 30]), tensor([11, 12, 13]))