In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

torch.__version__

'1.12.1+cpu'

In [10]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [11]:
scalar.ndim

0

In [12]:
scalar.item()

7

In [14]:
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [15]:
vector.ndim

1

In [23]:
MATRIX = torch.tensor([[7, 7,], [7, 7]])
MATRIX

tensor([[7, 7],
        [7, 7]])

In [18]:
MATRIX.ndim

2

In [21]:
MATRIX.shape

torch.Size([2, 2])

In [24]:
TENSOR = torch.tensor([[[1, 2, 3], [3, 4, 5], [5, 6, 7]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 4, 5],
         [5, 6, 7]]])

In [26]:
TENSOR.shape

torch.Size([1, 3, 3])

RANDOM TENSORS

In [34]:
random_tensor = torch.rand(3, 4, 3)
random_tensor

tensor([[[0.0953, 0.2031, 0.0353],
         [0.8023, 0.6688, 0.7867],
         [0.5773, 0.2235, 0.9626],
         [0.9743, 0.0100, 0.1975]],

        [[0.3476, 0.6243, 0.9167],
         [0.7092, 0.0347, 0.9206],
         [0.7520, 0.8353, 0.5062],
         [0.2279, 0.9417, 0.9281]],

        [[0.2809, 0.5736, 0.9174],
         [0.9001, 0.6840, 0.0831],
         [0.9902, 0.1364, 0.5928],
         [0.8995, 0.9227, 0.4634]]])

In [41]:
random_image_size_tensor = torch.rand(244, 244, 3)
random_image_size_tensor

tensor([[[0.7585, 0.4767, 0.8843],
         [0.6614, 0.0611, 0.6333],
         [0.1302, 0.5796, 0.2695],
         ...,
         [0.2884, 0.9599, 0.7126],
         [0.0777, 0.0420, 0.7149],
         [0.7502, 0.4438, 0.2079]],

        [[0.7020, 0.0882, 0.3419],
         [0.3000, 0.1922, 0.9312],
         [0.0292, 0.9491, 0.2624],
         ...,
         [0.2843, 0.5429, 0.9844],
         [0.3959, 0.6897, 0.5016],
         [0.4399, 0.8573, 0.0179]],

        [[0.9392, 0.6637, 0.7064],
         [0.0478, 0.8146, 0.5778],
         [0.0296, 0.6500, 0.9654],
         ...,
         [0.5016, 0.9138, 0.4969],
         [0.8266, 0.0535, 0.0231],
         [0.1588, 0.2966, 0.4984]],

        ...,

        [[0.5516, 0.8579, 0.8532],
         [0.0902, 0.9962, 0.2429],
         [0.3965, 0.5582, 0.0700],
         ...,
         [0.4697, 0.5311, 0.1351],
         [0.1568, 0.9747, 0.7750],
         [0.6410, 0.0202, 0.6475]],

        [[0.1384, 0.6874, 0.0806],
         [0.1859, 0.8185, 0.8630],
         [0.

In [43]:
zeros = torch.zeros(3, 4)
ones = torch.ones(3, 4)

In [44]:
zeros, ones

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]))