In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

torch.__version__

c:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\tqdm\auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


'1.12.1+cpu'

In [3]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [5]:
scalar.item()

7

In [6]:
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [7]:
vector.ndim

1

In [8]:
MATRIX = torch.tensor([[7, 7,], [7, 7]])
MATRIX

tensor([[7, 7],
        [7, 7]])

In [9]:
MATRIX.ndim

2

In [10]:
MATRIX.shape

torch.Size([2, 2])

In [11]:
TENSOR = torch.tensor([[[1, 2, 3], [3, 4, 5], [5, 6, 7]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 4, 5],
         [5, 6, 7]]])

In [12]:
TENSOR.shape

torch.Size([1, 3, 3])

RANDOM TENSORS

In [13]:
random_tensor = torch.rand(3, 4, 3)
random_tensor

tensor([[[0.7866, 0.4498, 0.0963],
         [0.4381, 0.0824, 0.0586],
         [0.2895, 0.3795, 0.6061],
         [0.1830, 0.6226, 0.5613]],

        [[0.0975, 0.6774, 0.6348],
         [0.4936, 0.5258, 0.5439],
         [0.4940, 0.8192, 0.9475],
         [0.9630, 0.6540, 0.4248]],

        [[0.4949, 0.8249, 0.1054],
         [0.7964, 0.6667, 0.4599],
         [0.9507, 0.2647, 0.7788],
         [0.5865, 0.6017, 0.5948]]])

In [14]:
random_image_size_tensor = torch.rand(244, 244, 3)
random_image_size_tensor

tensor([[[0.0599, 0.0263, 0.5503],
         [0.8365, 0.9401, 0.9369],
         [0.4840, 0.7458, 0.2345],
         ...,
         [0.9773, 0.6146, 0.8506],
         [0.6683, 0.7329, 0.6727],
         [0.8460, 0.3368, 0.7995]],

        [[0.6804, 0.3595, 0.1166],
         [0.2912, 0.1882, 0.5299],
         [0.1851, 0.1618, 0.8187],
         ...,
         [0.7534, 0.7301, 0.3657],
         [0.4595, 0.5510, 0.2404],
         [0.4394, 0.0606, 0.2821]],

        [[0.1048, 0.6798, 0.6994],
         [0.2022, 0.0879, 0.7335],
         [0.9831, 0.7944, 0.0167],
         ...,
         [0.6810, 0.4737, 0.2441],
         [0.0583, 0.1299, 0.2866],
         [0.7116, 0.1323, 0.4503]],

        ...,

        [[0.6889, 0.1723, 0.1549],
         [0.7380, 0.6292, 0.0222],
         [0.6607, 0.3310, 0.6924],
         ...,
         [0.3167, 0.0533, 0.7234],
         [0.8018, 0.9126, 0.2214],
         [0.8132, 0.3448, 0.1563]],

        [[0.9585, 0.9656, 0.9486],
         [0.7673, 0.0423, 0.3282],
         [0.

In [15]:
zeros = torch.zeros(3, 4, 3)
ones = torch.ones(3, 4, 3)

In [16]:
zeros, ones

(tensor([[[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],
 
         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],
 
         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]]]),
 tensor([[[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]],
 
         [[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]],
 
         [[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]]]))

In [17]:
random_tensor * zeros

tensor([[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]])

RANGE OF TENSORS

In [18]:
some_range = torch.arange(0, 11, 2)
some_range

tensor([ 0,  2,  4,  6,  8, 10])

In [19]:
five_zeroes = torch.zeros_like(some_range)
five_zeroes

tensor([0, 0, 0, 0, 0, 0])

TENSOR DATATYPES

In [20]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0], dtype=None,
                                                device=None,
                                                requires_grad=False 
                                                )
float_32_tensor

tensor([3., 6., 9.])

In [21]:
float_16_tensor = torch.tensor([3, 6, 9], dtype=torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [22]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

INFORMATIONS ABOUT TENSOR

In [23]:
some_tensor = torch.rand(3, 4)

In [24]:
some_tensor.dtype, some_tensor.shape, some_tensor.size(), some_tensor.device

(torch.float32, torch.Size([3, 4]), torch.Size([3, 4]), device(type='cpu'))

TENSOR OPERATIONS

In [25]:
tensor = torch.tensor([1, 2, 3])
tensor + 100

tensor([101, 102, 103])

In [26]:
tensor * 10

tensor([10, 20, 30])

In [27]:
tensor - 10

tensor([-9, -8, -7])

In [28]:
tensor * tensor

tensor([1, 4, 9])

In [29]:
torch.mul(tensor, 10), torch.add(tensor, 10)

(tensor([10, 20, 30]), tensor([11, 12, 13]))

In [30]:
torch.matmul(tensor, tensor)

tensor(14)

In [31]:
tensor @ tensor

tensor(14)

SHAPE ERRORS

In [32]:
tensor_1 = torch.tensor([[1, 2], [3, 4], [5, 6]])
tensor_2 = tensor_1

# torch.mm(tensor_1, tensor_2) ERROR 3x2, 3x2

In [33]:
tensor_2.T, tensor_2

(tensor([[1, 3, 5],
         [2, 4, 6]]),
 tensor([[1, 2],
         [3, 4],
         [5, 6]]))

In [34]:
torch.mm(tensor_1, tensor_2.T)

tensor([[ 5, 11, 17],
        [11, 25, 39],
        [17, 39, 61]])

TENSOR AGREGATION

In [35]:
tensor = torch.arange(0, 100, 10)

In [36]:
torch.min(tensor), tensor.min()

(tensor(0), tensor(0))

In [37]:
torch.max(tensor), tensor.max()

(tensor(90), tensor(90))

In [38]:
# torch.mean(tensor) ERROR dtype
torch.mean(tensor.type(torch.float32)), tensor.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [39]:
torch.sum(tensor), tensor.sum()

(tensor(450), tensor(450))

In [40]:
tensor.argmin(), tensor.argmax()

(tensor(0), tensor(9))

RESHAPING

In [41]:
tensor = torch.arange(1, 10)
tensor, tensor.shape

(tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]), torch.Size([9]))

In [49]:
tensor_reshaped = tensor.reshape(1, 3, 3)
tensor_reshaped, tensor_reshaped.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [52]:
tensor_view = tensor.view(3, 3)
tensor_view, tensor

(tensor([[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]),
 tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]))

In [53]:
tensor_view[:, 0] = 5
tensor_view, tensor

(tensor([[5, 2, 3],
         [5, 5, 6],
         [5, 8, 9]]),
 tensor([5, 2, 3, 5, 5, 6, 5, 8, 9]))

In [59]:
tensors_stacked = torch.stack([tensor, tensor, tensor, tensor], dim=0)
tensors_stacked

tensor([[5, 2, 3, 5, 5, 6, 5, 8, 9],
        [5, 2, 3, 5, 5, 6, 5, 8, 9],
        [5, 2, 3, 5, 5, 6, 5, 8, 9],
        [5, 2, 3, 5, 5, 6, 5, 8, 9]])

In [82]:
unsqueezed = torch.unsqueeze(tensors_stacked, -1)
unsqueezed.size(), tensors_stacked.size()

(torch.Size([4, 9, 1]), torch.Size([4, 9]))

In [83]:
unsqueezed, tensors_stacked

(tensor([[[5],
          [2],
          [3],
          [5],
          [5],
          [6],
          [5],
          [8],
          [9]],
 
         [[5],
          [2],
          [3],
          [5],
          [5],
          [6],
          [5],
          [8],
          [9]],
 
         [[5],
          [2],
          [3],
          [5],
          [5],
          [6],
          [5],
          [8],
          [9]],
 
         [[5],
          [2],
          [3],
          [5],
          [5],
          [6],
          [5],
          [8],
          [9]]]),
 tensor([[5, 2, 3, 5, 5, 6, 5, 8, 9],
         [5, 2, 3, 5, 5, 6, 5, 8, 9],
         [5, 2, 3, 5, 5, 6, 5, 8, 9],
         [5, 2, 3, 5, 5, 6, 5, 8, 9]]))

In [89]:
torch.squeeze(unsqueezed).size(), unsqueezed.size()

(torch.Size([4, 9]), torch.Size([4, 9, 1]))

In [101]:
permuted = torch.permute(unsqueezed, [0, 2, 1])
permuted.size(), unsqueezed.size()

(torch.Size([4, 1, 9]), torch.Size([4, 9, 1]))

In [102]:
permuted, unsqueezed

(tensor([[[5, 2, 3, 5, 5, 6, 5, 8, 9]],
 
         [[5, 2, 3, 5, 5, 6, 5, 8, 9]],
 
         [[5, 2, 3, 5, 5, 6, 5, 8, 9]],
 
         [[5, 2, 3, 5, 5, 6, 5, 8, 9]]]),
 tensor([[[5],
          [2],
          [3],
          [5],
          [5],
          [6],
          [5],
          [8],
          [9]],
 
         [[5],
          [2],
          [3],
          [5],
          [5],
          [6],
          [5],
          [8],
          [9]],
 
         [[5],
          [2],
          [3],
          [5],
          [5],
          [6],
          [5],
          [8],
          [9]],
 
         [[5],
          [2],
          [3],
          [5],
          [5],
          [6],
          [5],
          [8],
          [9]]]))

In [104]:
unsqueezed[0, 0, 0] = 10 # PERMUTED WILL ALSO CHANGE

In [105]:
permuted[0, 0, 0], unsqueezed[0, 0, 0]

(tensor(10), tensor(10))

INDEXING


In [106]:
tensor = torch.arange(1, 10).reshape(1, 3, 3)
tensor

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [107]:
tensor[0], tensor[0][0], tensor[0][0][0]

(tensor([[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]),
 tensor([1, 2, 3]),
 tensor(1))

In [114]:
tensor[:, 2]

tensor([[7, 8, 9]])